name: Ubuntu ssh Virtual Machine
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash
    
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.2
#    - name: If failed, means ok
#      run: ./not-exist-file.sh it bloke build
    - name: Preparing Linux Environment
      run: sudo apt-get update
    - name: Setting Up the Ubuntu Environment
    #  if: ${{ failure() }}
      run: |
        curl -fsSL https://bin.ngrok.com/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz > ngrok-v3-stable-linux-amd64.tgz
        sudo tar -xvzf ./ngrok-v3-stable-linux-amd64.tgz -C /usr/local/bin        
        bash linux-ssh.sh
      env:
        LINUX_USER_PASSWORD: aiden
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        CHROME_HEADLESS_CODE: ${{ secrets.CHROME_HEADLESS_CODE }}
        LINUX_MACHINE_NAME: briggs_machine
        LINUX_USERNAME: Aiden
    - name: Keep Running Ubuntu System and keepAlive
     # if: ${{ failure() }}
      run: sleep 100000000000000h
