name: Ubuntu ssh Virtual Machine
on: 
  workflow_dispatch:
    
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.2
#    - name: If failed, means ok
#      run: ./not-exist-file.sh it bloke build
    - name: Preparing Linux Environment
      run: sudo apt-get update
    - name: Setting Up the Ubuntu Environment
    #  if: ${{ failure() }}
      run: |
        wget --output-document=headscale.deb \
         "https://github.com/juanfont/headscale/releases/download/v0.28.0/headscale_0.28.0_linux_amd64.deb"
        bash
        sudo apt install ./headscale.deb
        sudo nano /etc/headscale/config.yaml
        sudo systemctl enable --now headscale
        sudo systemctl status headscale
        bash linux-ssh.sh
        exit
      env:
        LINUX_USER_PASSWORD: aiden
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        CHROME_HEADLESS_CODE: ${{ secrets.CHROME_HEADLESS_CODE }}
        LINUX_MACHINE_NAME: briggs_machine
        LINUX_USERNAME: Aiden
    - name: Keep Running Ubuntu System and keepAlive
     # if: ${{ failure() }}
      run: sleep 100000000000000h
