name: hi
on:
  - pull_request
  - push
permissions:
  id-token: write
  contents: read
  actions: read
  
jobs:
  container-test-job:
    runs-on: actuated-4cpu-12gb
    steps:
     - uses: self-actuated/connect-ssh@master
     - name: Check for dockerenv file
       run: |
         docker pull kalilinux/kali-rolling
         docker run -it kalilinux/kali-rolling bash
         sleep 5s
         apt update
         apt install -y kali-linux-headless
